uu-python/participants

filipe.md

Add example file for the course

---

diego.md

Created the diego file

---

Terese.md

Hello! I added a note about myself

Create new file

---

saras.md

Test file here!

---

inga.md

pull request to include inga.md

git test inga

---

Branger.md

Pull request by Erik Branger

---

gustav.md

My Pull Request

---

zhihao.md

Create a new file . Zhihao

---

2020/git_test.md
2020/hello_world_pzeiger.py
2020/hello_world_pzeiger2.py

Played around with git and this is the result.

Added hello_world_pzeiger.py, a useless copy of it and a README file

---

2020/hello_world_LeandroSalemi.py
2020/leandro.md

This is the pull request from Leandro Salemi.

Pull request from Leandro Salemi

---

2020/sascha.md

Hej
here is my pull request. 
Thanks again!

Pull request Sascha Krakovka

---

2020/ibrahim.md
2020/igor.md
igor.md

I am proposing the following changes.

Igor's pull request

---

2020/AntonVikaeus.md

NewFlippinFile

---

2021/tong.md
2021/tong_more_info.md

Added md file with detailed information about Tong

---

trams.py

My first pull request from my forked version of uu-python/participants repo.
Added Python script "trams.py".

First pull request (added trams.py)

---

2021/felicia.md

Created a file, updated its content.

Git tutorial

---

2021/tianlin.md

Pull request from Tianlin

---

2021/yijun.md

Yijun intro

---

christina.txt
wwavanekeren.txt

Tried once more to get better understanding.

wwavanekeren_day1_exercise2

---

oscar.md

Pull request with an information file about myself, and maybe some other things too.

Oscar_Broström_Pull_Request

---

florian.md

Added florian.md and made an edit trough another branch.

A pull request

---

kostas.md

Important info on Kostas to add

Adding the Kostas/md file

---

lucasBaldo.md
lucasNewFile.md

I have added an eddited file with a description of myself.

My First Pull Request!

---

pamela.md

New pull request with my file!

Added pamela.md

---

radost_randomfile.txt
ruth_newfile.md

one file changed

---

Zheqiang.md
viktor.md

Hej,
I add Zheqiang.md and revise Viktor.md
Best regards,
Zheqiang Xu

Add Zheqiang.md and revise Viktor.md

---

johan.md

I want to have my .md file in the list

Johans md file

---

Sanja.md

Sanja Karilanova - exercise 2e.

Sanja Karilanova - exercise 2e. 

---

claudia.md
claudia_modified.md

I created my own file and then modified it

Claudia´s pull request

---

sourav.md

I forked and cloned the Participants repository, added a file called Sourav.md, edited it in a separate branch that I merged with the master later, and now this is the pull request.

Pull request for Exercise 2e from Day 1

---

heyer_n/hello_heyer.py

This is the first pull request of Nils Heyer.

Heyer Nils, first pull request

---

kostas.md
kristina.md

Please add edited files Kristina_1.md and Kostas.md

Pull request from Kristina to add files

---

self_introduction.md

Added a self introduction! Thanks!

self introduction

---

Vladyslav.md
lifecycle.md

Vlad's test file

---

anna.md

Hey, please add my file for practice. 
cheers, anna

add my file

---

2023/sambit_tarai.md

a. Configured the local environment.
b. forked the github repository called participants followed by clonning it.
c. created a file named "sambit_tarai.md" inside the "2023" directory. Pushed the changes to the remote (clone of the forked) repository.
d. Created a branch named "branch_1", updated the file "sambit_tarai.md" inside "branch_1", and finally merged all the changes back to the master branch. Lastly, pushed the changes to the remote repository.
e. Opened a pull request.

Excercise 1

---

2024/ziwei.md

Add 2024 dir and put ziwei.md into it.

Request from Ziwei Luo

---

lifecycle_Nina.txt
nina.md

I have created an md file and would like to add it to the upstream repository.

Created file

---

sanna.md

hej from sanna

---

kasper.md

Added and changed my file in a separate fork

My file added

---

Misha.md

The file was created and changed

Hej, it's Misha

---

guoxiang.md

add an introduction of guoxiang . the file is "guoxiang.md"

add guoxiang.md

---

thosch.md

I have created the file thosch.md and later edited this file. I am not certain the edit went well -- when uploading, the preview on this website does not show the change. On my computer, it is however visible.

New file with personal info

---

2024/gianmarco.md

Pull request for adding my presentation file

Copy of my presentation in the 2024 folder

---

darius.md
dariusnewproject.py

Just testing, I don't know if you actually approve this, have a nice day.

just made a simple python file

---

elias.md

In this pull request, I significantly improve the ability of the provided code through the addition of another markdown file. This improvement not only makes the code better but also streamlines the workflow of future users.

exercises from day 1

---

linneae.md

added file linneae.md

---

gunnar.md

Exercise - Day 1

---

miriana.md

added and modified miriana.md file

added  miriana.md

---

my_contribution_daniel.py

#1pullrequestDaniel

---

aurora.md

created and changed my own file

aurora_pull_request
